CET/config/routes.rb
CET::Application.routes.draw do
  devise_for :users

  resources :contracts do 
    member do 
      post 'sales_type' 
      post "sales_txn_type"
    end
    collection do 
      post 'sales_type' 
      post "sales_txn_type"
      post "sales_counselor"
      post "sales_lead_source"
      post "item_group_code"
      post "item_category_code"
      post "payment_type"
      post "interest_term"
      post "interest_method"
      post "user_password"
      post "user_location"
      post "usernames"
      post "customer_search"
      post "item_search"
      post "recieve_payment"
    end
  end

    root :to => "contracts#index"

end

CET/app/models/contract.rb
class Contract < ActiveRecord::Base
  validates_presence_of :contract_no, :location_id
  validates_uniqueness_of :contract_no
  validates_numericality_of :contract_no, :on => [:create, :update]
  validates_numericality_of :location_id, :on => [:create, :update]
  
  attr_accessible :contract_no, :location_id
  belongs_to :user
  
  
  before_save :json_serialize
  #after_save  :json_deserialize
  after_find  :json_deserialize
  
  attr_writer :current_step, :sales_batch_date, :sales_txn_date, :sales_date, :username, :sales_type, :sales_need, 
  :sales_txn_type, :sales_lead_source, :sales_primary_counselor, :sales_secondary_counselor_1
  
  def current_step
		@current_step || steps.first
	end
	
	def steps
		%w[contract_detail personal_detail item_detail payment_detail summary]
	end
	
	def next_step
		self.current_step = steps[steps.index(current_step) + 1]
	end
	
	def previous_step
		self.current_step = steps[steps.index(current_step) - 1 ]
	end
	
	def first_step?
		current_step == steps.first
	end
	
	def last_step?
		current_step == steps.last
	end
  
  def json_serialize  
    self.data = ActiveSupport::JSON.encode(self.attributes['data'])
  end

  def json_deserialize
    unless (self.attributes['data'].nil?)
      self.data = ActiveSupport::JSON.decode(self.attributes['data'].to_s)
    end
  end

  
  def async_contract_entry
    Resque.enqueue(PdfQueue, self.id)
    Resque.enqueue(XlsQueue, self.id)
    Resque.enqueue(CompressQueue, self.id)
    Resque.enqueue(MailQueue, self.id)
  end
  
  def sales_batch_date
  	@sales_batch_date || self.data['sales_batch_date']
  end
  
  def sales_txn_date
  	@sales_txn_date || self.data['sales_txn_date']
  end
  
  def sales_date
  	@sales_date || self.data['sales_date']
  end
  
  def username
 		@username || self.data['username'] 	
  end
  
  def password
  	@password || self.data["password"]
  end
  
  def sales_type
  	@sales_type || self.data["sales_type"]
  end

	def sales_need
		@sales_need || self.data["sales_need"]	
	end
	
	def sales_txn_type
		@sales_txn_type || self.data["sales_txn_type"]
	end
	
	def sales_lead_source
		@sales_lead_source || self.data["sales_lead_source"]
	end
	
	def sales_primary_counselor
		@sales_primary_counselor  || self.data["sales_primary_counselor"]
	end
	
	def sales_secondary_counselor_1
		@sales_secondary_counselor_1 || self.data["sales_secondary_counselor_1"]
	end
	
end

CET/app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :new, :edit]
  
  def index
    @contracts = current_user.contracts.all rescue nil
    session[:cstep] = session[:cparams] = nil
    respond_to do |format|
       format.html{ }
    end
  end

  def new
    session[:cparams] ||= {}
    @contract = current_user.contracts.new(session[:cparams])
    @contract.data = session[:cparams]
    @users = HMIS::users
    #@locations = HMIS::locations(current_user.email)
    @sales_need = HMIS::sales_need()
    @name_types = HMIS::name_types()
    @discount_reason = HMIS::get_discount_reason
    #@upload_type = HMIS::file_upload_type
    session[:cstep] = params['q'].blank? ? session[:cstep] : params['q']
    @contract.current_step = session[:cstep]
    if @contract.current_step == "personal_detail"
        @personal_details = session[:cparams]["personal"] unless session[:cparams]["personal"].nil?
    end
    if @contract.current_step == "item_detail"
        @item_details = session[:cparams]["item"] unless session[:cparams]["item"].nil?
    end
    
    if @contract.current_step == "payment_detail"
        @payment_details = session[:cparams]["payment"] unless session[:cparams]["payment"].nil?
        @interest_term =  session[:cparams]["interest_term"].nil? ? "" : session[:cparams]["interest_term"]
        @interest_payment_start_date = session[:cparams]["interest_payment_start_date"].nil? ? "" : session[:cparams]["interest_payment_start_date"] 
        @interest_method = session[:cparams]["interest_method"].nil? ? "" : session[:cparams]["interest_method"] 
        @interest_rate = session[:cparams]["interest_rate"].nil? ? "" : session[:cparams]["interest_rate"] 
        @interest_free_days = session[:cparams]["interest_free_days"].nil? ? "" : session[:cparams]["interest_free_days"] 
        @interest_forgive = session[:cparams]["interest_forgive"].nil? ? "" : session[:cparams]["interest_forgive"] 
    end
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    session[:cparams].deep_merge!(params[:contract]) if params[:contract]
    @contract = current_user.contracts.new(session[:cparams])
    @contract.current_step = session[:cstep]
    @contract.data = session[:cparams] #JSON.parse(params[:contract].to_json)
    
    if @contract.valid?
      if params[:back_button]
        @contract.previous_step
      elsif @contract.last_step?
        @contract.save #if @order.all_valid?
      else
        @contract.next_step
      end
      session[:cstep] = @contract.current_step
    end
    
    
    respond_to do |format|
      unless @contract.new_record?
        @contract.async_contract_entry()
        session[:cstep] = session[:cparams] = nil
        format.html{ redirect_to contracts_url, :notice => "Your contract has been queued for generation. You will receive an email with all files shortly at #{current_user.email}" }
      else
        #flash[:error] = "Error Occured"
        format.html { redirect_to(:action => "new") }
      end
     end
  end

  def edit
    session[:cparams] ||= {}
    @contract = current_user.contracts.find(params[:id])
    session[:cparams] = @contract.data #json_deserialize

    @users = HMIS::users
    #@locations = HMIS::locations(current_user.email)
    @sales_need = HMIS::sales_need()
    @name_types = HMIS::name_types()
    @discount_reason = HMIS::get_discount_reason
    #@upload_type = HMIS::file_upload_type
    session[:cstep] = params['q'].blank? ? session[:cstep] : params['q']
    @contract.current_step = session[:cstep]
    if @contract.current_step == "personal_detail"
        @personal_details = session[:cparams]["personal"] unless session[:cparams]["personal"].nil?
    end
    if @contract.current_step == "item_detail"
        @item_details = session[:cparams]["item"] unless session[:cparams]["item"].nil?
    end
    
    if @contract.current_step == "payment_detail"
        @payment_details = session[:cparams]["payment"] unless session[:cparams]["payment"].nil?
        @interest_term =  session[:cparams]["interest_term"].nil? ? "" : session[:cparams]["interest_term"]
        @interest_payment_start_date = session[:cparams]["interest_payment_start_date"].nil? ? "" : session[:cparams]["interest_payment_start_date"] 
        @interest_method = session[:cparams]["interest_method"].nil? ? "" : session[:cparams]["interest_method"] 
        @interest_rate = session[:cparams]["interest_rate"].nil? ? "" : session[:cparams]["interest_rate"] 
        @interest_free_days = session[:cparams]["interest_free_days"].nil? ? "" : session[:cparams]["interest_free_days"] 
        @interest_forgive = session[:cparams]["interest_forgive"].nil? ? "" : session[:cparams]["interest_forgive"] 
    end
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def update
    session[:cparams].deep_merge!(params[:contract]) if params[:contract]
    @contract = current_user.contracts.find(params[:id])
    @contract.current_step = session[:cstep]
    @contract.data = session[:cparams] #JSON.parse(params[:contract].to_json)
    
    respond_to do |format|
      @contract.update_attributes(:contract_no => @contract.data["contract_no"], :location_id => @contract.data["location_id"])
      if params[:back_button]
        @contract.previous_step
      elsif @contract.last_step?
        session[:cstep] = session[:cparams] = nil
        @contract.async_contract_entry()
        format.html{ redirect_to contracts_url, :notice => "Your contract has been queued for generation. You will receive an email with all files shortly at #{current_user.email}" }
      else
        @contract.next_step
      end
      session[:cstep] = @contract.current_step
      format.html { redirect_to(:action => "edit") }
    end
  end
  
  def customer_search
    fname = params[:customer_search][:fname].downcase == "first name"  ? "" : params[:customer_search][:fname]
    lname = params[:customer_search][:lname].downcase == "last name"  ? "" : params[:customer_search][:fname]
    zipcode = params[:customer_search][:zipcode].downcase == "zipcode"  ? "" : params[:customer_search][:fname]
    phone = params[:customer_search][:phone].downcase == "phone"  ? "" : params[:customer_search][:fname]
    @result = HMIS::customer_search(:first_name => fname, :last_name => lname, :zipcode => zipcode, :phone => phone)
    respond_to do |format|
       format.json{ render :json => @result }
     end
  end
  
  def item_search
    code, desc, group_code, category_code = params[:item_search][:item_code],params[:item_search][:item_desc], params[:item_search][:group_code], params[:item_search][:category_code]
    @result = HMIS::item_search(:code => code, :desc => desc, :group_code => group_code, :category_code => category_code)
    respond_to do |format|
       format.json{ render :json => @result }
     end 
  end
  
  def usernames
    @users = HMIS::users
     respond_to do |format|
       format.json{ render :json => @users }
     end
  end
  
  def user_password
    user_id = params[:user_id].blank? ? nil : params[:user_id]
    @password = user_id.blank? ? [] : HMIS::user_password(user_id)
     respond_to do |format|
       format.html{ render :text => @password }
     end
  end
  
  def user_location
    user_id = params[:user_id].blank? ? nil : params[:user_id]
    @locations = user_id.blank? ? [] : HMIS::locations(user_id)
     respond_to do |format|
       format.json{ render :json => @locations }
       #format.html{ render :partial => 'properties', :layout=>false, :locals => {:item => @locations} }
     end
  end
  
  def sales_type
    location_id = params[:location_id].blank? ? nil : params[:location_id]
    @sale_types = location_id.blank? ? [] : HMIS::get_sales_type(location_id)
     respond_to do |format|
       format.json{ render :json => @sale_types }
       #format.html{ render :partial => 'properties', :layout=>false, :locals => {:item => @sale_types} }
     end
  end 
  
  def sales_txn_type
    sales_type_id = params[:sales_type_id].blank? ? nil : params[:sales_type_id]
    @sales_txn_types = sales_type_id.blank? ? [] : HMIS::get_sales_txn_type(sales_type_id)
     respond_to do |format|
       format.json{ render :json => @sales_txn_types }
       #format.html{ render :partial => 'properties', :layout=>false, :locals => {:item => @sales_txn_types } }
     end
  end  
  
  def sales_counselor
    sales_type_id = params[:sales_type_id].blank? ? nil : params[:sales_type_id]
    @sales_counselor = sales_type_id.blank? ? [] : HMIS::get_sales_counselor(sales_type_id)
     respond_to do |format|
       format.json{ render :json => @sales_counselor }
       #format.html{ render :partial => 'properties', :layout=>false, :locals => {:item => @sales_counselor } }
     end
  end
  
  def sales_lead_source
    sales_txn_type_id = params[:sales_txn_type_id].blank? ? nil : params[:sales_txn_type_id]
    @lead_sources = sales_txn_type_id.blank? ? [] : HMIS::get_sales_lead_source(sales_txn_type_id)
     respond_to do |format|
       format.json{ render :json => @lead_sources }
       #format.html{ render :partial => 'properties', :layout=>false, :locals => {:item => @lead_sources } }
     end
  end
  
  def item_group_code
    location_id = params[:location_id].blank? ? nil : params[:location_id]
    @group_codes = location_id.blank? ? [] : HMIS::get_group_codes(location_id)
     respond_to do |format|
       format.json{ render :json => @group_codes }
       #format.html{ render :partial => 'properties', :layout=>false, :locals => {:item => @group_codes } }
     end
  end
  
  def item_category_code
    group_code_id = params[:group_code_id].blank? ? nil : params[:group_code_id]
    @category_codes = group_code_id.blank? ? [] : HMIS::get_category_codes(group_code_id)
     respond_to do |format|
       format.json{ render :json => @category_codes }

CET/app/helpers/contracts_helper.rb
module ContractsHelper
	def select_box(id, collection , options = {} )
		{:include_blank => true}.merge!(options)
		select_tag(id, options_for_select(collection), options )
	end
	
	def total_cost(contract)
		items = contract.data["item"]
		total_cost = 0
		(1..items.length).each do |i|
			price = items[i.to_s]["price"].to_f * items[i.to_s]["quantity"].to_i
			discount = price * items[i.to_s]["discount_percent"].to_f / 100
			total_cost += (price - discount)
		end
		return total_cost
	end
end

CET/app/views/contracts/_file_upload.html.erb
<table class="customers">
	<tbody>
		<tr>
			<th>Image names</th>
			<th>Document type</th>
			<th>Upload file</th>
		</tr>

		<% (1..3).each do |item| %>
			<tr class=<%= item%2 == 0 ? "alt" : ""%>>
				<td>
				<%= text_field_tag "contract[file][#{item}][image_name]", "", :size => 10 %>
				</td>
				<td>
				<%= select_box("contract[file][#{item}][upload_type]", @upload_type, :style => "width: 270px;") %>
				</td>
				<td>
				<%= file_field_tag "contract[file][#{item}][upload_file]" %>
				</td>
			</tr>
		<% end %>

	</tbody>
</table>

<br />
<br />

CET/app/views/contracts/_item_detail_step.html.erb
<table class="customers">
  <tbody>
    <tr>
      <th>Item code</th>
      <th>Item Description</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Discount%</th>
      <th>Discount reason</th>
    </tr>

		<% (1..5).each do |item| %>
		<tr class=<%= item%2 == 0 ? "alt" : ""%>>
			<td>
				<%= text_field_tag "contract[item][#{item}][final_code]", (@item_details.nil? ? "" : @item_details[item.to_s]["final_code"]), :size => 20  %>
			</td>
			<td>
				<%= text_field_tag "contract[item][#{item}][final_desc]", (@item_details.nil? ? "" : @item_details[item.to_s]["final_desc"]), :size => 30 %>
			</td>
			<td>
				<%= text_field_tag "contract[item][#{item}][quantity]", (@item_details.nil? ? "" : @item_details[item.to_s]["quantity"]), :size => 5 %>
			</td>
			<td>
				<%= text_field_tag "contract[item][#{item}][price]", (@item_details.nil? ? "" : @item_details[item.to_s]["price"]), :size => 10  %>
			</td>
			<td>
				<%= text_field_tag "contract[item][#{item}][discount_percent]", (@item_details.nil? ? "" : @item_details[item.to_s]["discount_percent"]), :size => 10  %>
			</td>
			<td>
				<%#= select_box("contract[item][#{item}][discount_reason]", @discount_reason) %>
				<%= text_field_tag "contract[item][#{item}][discount_reason]", (@item_details.nil? ? "" : @item_details[item.to_s]["discount_reason"]), :size => 30 %>
				<script type="text/javascript" charset="utf-8">
					$("#contract_item_<%= item.to_s %>_discount_reason").autocomplete({
						source : <%= sanitize(@discount_reason.to_json) %>
					});
				</script>
			</td>
			<td><%= link_to image_tag("icon-clear.gif"), "javascript:void(0);", :onclick => "$(this).clearRow(#{item})" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
  
<br />
<br />

CET/app/views/contracts/edit.html.erb
<% if @contract.current_step == "personal_detail" %>
  <% title "Customer Details" %>
  <div class="search_details green">
	  Would you like to search for an existing Purchaser?
  </div>
  <br />
	<div>
		<%= form_tag('/contracts/customer_search', :id => "customer_search") do -%>
			<%= text_field_tag "customer_search[fname]", "First name", :class => "dull-txt", :onfocus => "$(this).clearfield('First name');", :onblur => "$(this).resetfield('First name');" %>
			<span>or</span>
			<%= text_field_tag "customer_search[lname]", "Last name", :class => "dull-txt", :onfocus => "$(this).clearfield('Last name');", :onblur => "$(this).resetfield('Last name');"%>
			<span>or</span>
			<%= text_field_tag "customer_search[zipcode]", "Zipcode", :class => "dull-txt", :onfocus => "$(this).clearfield('Zipcode');", :onblur => "$(this).resetfield('Zipcode');" %>
			<span>or</span>
			<%= text_field_tag "customer_search[phone]", "Phone", :class => "dull-txt", :onfocus => "$(this).clearfield('Phone');", :onblur => "$(this).resetfield('Phone');" %>
			<%= submit_tag "Search", :class => "button small blue" %>
		<% end -%>
	</div>

  <br />
  <br />
<% end%>

<% if @contract.current_step == "item_detail" %>
  <% title "Line Item Details" %>
  <div class="search_details green">
	  Would you like to search for an existing item?
  </div>
  <br />
  <div>
  	<%= form_tag('/contracts/item_search', :id => "item_search") do -%>
			<%= text_field_tag "item_search[item_code]", "Item code", :class => "dull-txt", :onfocus => "$(this).clearfield('Item code');", :onblur => "$(this).resetfield('Item code');"%>
			<span>Or</span>			
			<%= text_field_tag "item_search[item_desc]", "Item description", :class => "dull-txt", :onfocus => "$(this).clearfield('Item description');", :onblur => "$(this).resetfield('Item description');"%>
			<span>Or</span>
			<%= text_field_tag "item_search[group_code]", "Group code", :class => "ac_field dull-txt", :onfocus => "$(this).clearfield('Group code');", :onblur => "$(this).resetfield('Group code');"%>
			<span>Or</span>
			<%= text_field_tag "item_search[category_code]", "Category code", :class => "ac_field dull-txt", :onfocus => "$(this).clearfield('Category code');", :onblur => "$(this).resetfield('Category code');"%>
			<%= submit_tag "Search", :class => "button small blue" %>
	  <% end -%>
  </div>
  
  <script type="text/javascript" charset="utf-8">
		$("#item_search_group_code").group_codes(<%= @contract.data["location_id"] %>);  
  </script>

  <br />
  <br />

<% end %>


<%= form_for @contract, :html => { :multipart => true } do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "#{@contract.current_step}_step", :f => f %>
 <div class="right">
		<%= f.submit "Back", :name => "back_button", :class => "button blue" unless @contract.first_step? %>
		<%= f.submit "NEXT STEP", :class => "button blue" unless @contract.last_step? %>  
	 	<%= f.submit "Save & Generate Contract PDF", :class => "button blue" if @contract.last_step? %>
  </div>
  <div class="clear"></div>
<% end %>
<div class="right">
<p><%= link_to "Back to List", contracts_path, :class => "button small gray" %></p>
</div>
<div class="clear"></div>


<% if @contract.current_step == "payment_detail" %>
	<div id="cc_payment_details" style="display:none; position: absolute; margin-top: -290px; margin-left: 460px;" align="center">
		<%= form_tag('/contracts/recieve_payment', :id => "recieve_payment") do -%>
			<div class="success"></div>
			<div class="error" ></div>
			<br />
			<table class="customers">
				<tbody>
				  <tr>
				      <td><%= label_tag 'recieve_payment[full_name]', "Full Name" %></td>
				      <td><%= text_field_tag "recieve_payment[full_name]", "" %></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[card_number]', "Card Number" %></td>
				      <td><%= text_field_tag "recieve_payment[card_number]", "4111111111111111", :maxlength => 16, :class => "dull-txt", :onfocus => "$(this).clearfield('4111111111111111');", :onblur => "$(this).resetfield('4111111111111111');" %></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[expiry_date]', "Expiry Date" %></td>
				      <td><%= date_select "recieve_payment", "expiry_date", :start_year => Time.now.year, :end_year => Time.now.year + 10, :use_month_short => true, :order => [:month, :year], :include_blank => true %></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[cvv]', "CVV" %></td>
				      <td><%= password_field_tag "recieve_payment[cvv]", "", :maxlength => 3, :size => 3%></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[amount]', "Amount ($)" %></td>
				      <td><%= text_field_tag "recieve_payment[amount]", total_cost(@contract), :readonly => true %></td>
				  </tr>
				  
				</tbody>
			</table>
		<br />
		<%= submit_tag "Make Payment", :class => "button blue" %>
		<% end -%>
	</div>
<% end -%>

CET/app/views/contracts/index.html.erb
<% title "Contracts" %>

<% unless @contracts.blank? or current_user.blank? %>
<table class="customers">
  <tr>
    <th>Contract Number</th>
    <th>Location Id</th>
  </tr>
  <% for contract in @contracts %>
    <tr>
      <td><%= contract.contract_no %></td>
      <td><%= contract.location_id %></td>
      <td><%= link_to "Edit", edit_contract_path(contract), :class => "button gray small" %></td>
    </tr>
  <% end %>
</table>
<% end %>

<p><%= link_to "New Contract", new_contract_path, :class => "button blue" %></p>

CET/app/views/contracts/new.html.erb
<% if @contract.current_step == "personal_detail" %>
  <% title "Customer Details" %>
  <div class="search_details green">
	  Would you like to search for an existing Purchaser?
  </div>
  <br />
  <div>
  	<%= form_tag('/contracts/customer_search', :id => "customer_search") do -%>
			<%= text_field_tag "customer_search[fname]", "First name", :class => "dull-txt", :onfocus => "$(this).clearfield('First name');", :onblur => "$(this).resetfield('First name');" %>
			<span>or</span>
			<%= text_field_tag "customer_search[lname]", "Last name", :class => "dull-txt", :onfocus => "$(this).clearfield('Last name');", :onblur => "$(this).resetfield('Last name');"%>
			<span>or</span>
			<%= text_field_tag "customer_search[zipcode]", "Zipcode", :class => "dull-txt", :onfocus => "$(this).clearfield('Zipcode');", :onblur => "$(this).resetfield('Zipcode');" %>
			<span>or</span>
			<%= text_field_tag "customer_search[phone]", "Phone", :class => "dull-txt", :onfocus => "$(this).clearfield('Phone');", :onblur => "$(this).resetfield('Phone');" %>
			<%= submit_tag "Search", :class => "button small blue" %>
		<% end -%>
  </div>

  <br />
  <br />
<% end%>

<% if @contract.current_step == "item_detail" %>
  <% title "Line Item Details" %>
  <div class="search_details green">
	  Would you like to search for an existing item?
  </div>
  <br />
  <div>
  	<%= form_tag('/contracts/item_search', :id => "item_search") do -%>
			<%= text_field_tag "item_search[item_code]", "Item code", :class => "dull-txt", :onfocus => "$(this).clearfield('Item code');", :onblur => "$(this).resetfield('Item code');"%>
			<span>Or</span>			
			<%= text_field_tag "item_search[item_desc]", "Item description", :class => "dull-txt", :onfocus => "$(this).clearfield('Item description');", :onblur => "$(this).resetfield('Item description');"%>
			<span>Or</span>
			<%= text_field_tag "item_search[group_code]", "Group code", :class => "ac_field dull-txt", :onfocus => "$(this).clearfield('Group code');", :onblur => "$(this).resetfield('Group code');"%>
			<span>Or</span>
			<%= text_field_tag "item_search[category_code]", "Category code", :class => "ac_field dull-txt", :onfocus => "$(this).clearfield('Category code');", :onblur => "$(this).resetfield('Category code');"%>
			<%= submit_tag "Search", :class => "button small blue" %>
	  <% end -%>
  </div>
  
  <script type="text/javascript">
		$("#item_search_group_code").group_codes(<%= sanitize(@contract.data["location_id"].to_json) %>);  
  </script>

  <br />
  <br />

<% end %>


<%= form_for @contract, :html => { :multipart => true } do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "#{@contract.current_step}_step", :f => f %>
  <div class="right">
		<%= f.submit "Back", :name => "back_button", :class => "button blue" unless @contract.first_step? %>
		<%= f.submit "NEXT STEP", :class => "button blue" unless @contract.last_step? %>  
	 	<%= f.submit "Save & Generate Contract PDF", :class => "button blue" if @contract.last_step? %>
  </div>
  <div class="clear"></div>
<% end %>
<div class="right">
<p><%= link_to "Back to List", contracts_path, :class => "button small gray" %></p>
</div>
<div class="clear"></div>
  
<% if @contract.current_step == "payment_detail" %>
	<div id="cc_payment_details" style="display:none; position: absolute; margin-top: -290px; margin-left: 460px;" align="center">
		<%= form_tag('/contracts/recieve_payment', :id => "recieve_payment") do -%>
			<div class="success"></div>
			<div class="error" ></div>
			<br />
			<table class="customers">
				<tbody>
				  <tr>
				      <td><%= label_tag 'recieve_payment[full_name]', "Full Name" %></td>
				      <td><%= text_field_tag "recieve_payment[full_name]", "" %></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[card_number]', "Card Number" %></td>
				      <td><%= text_field_tag "recieve_payment[card_number]", "4111111111111111", :maxlength => 16, :class => "dull-txt", :onfocus => "$(this).clearfield('4111111111111111');", :onblur => "$(this).resetfield('4111111111111111');" %></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[expiry_date]', "Expiry Date" %></td>
				      <td><%= date_select "recieve_payment", "expiry_date", :start_year => Time.now.year, :end_year => Time.now.year + 10, :use_month_short => true, :order => [:month, :year], :include_blank => true %></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[cvv]', "CVV" %></td>
				      <td><%= password_field_tag "recieve_payment[cvv]", "", :maxlength => 3, :size => 3%></td>
				  </tr>
				  
				  <tr>
				      <td><%= label_tag 'recieve_payment[amount]', "Amount ($)" %></td>
				      <td><%= text_field_tag "recieve_payment[amount]", total_cost(@contract), :readonly => true %></td>
				  </tr>
				  
				</tbody>
			</table>
		<br />
		<%= submit_tag "Make Payment", :class => "button blue" %>
		<% end -%>
	</div>
<% end -%>